name: Run Hourly Sync

on:
  schedule:
    - cron: '0 */2 * * *' # Runs at 0 minutes past the hour, every 2 hours
  workflow_dispatch:
jobs:
  run:
    runs-on: windows-latest
    timeout-minutes: 50

    steps:
      - uses: actions/checkout@v4

      - name: Install NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore packages
        run: nuget restore ./HSH.TurumShopifySyncApp.sln

      - name: Build app
        run: dotnet build ./HSH.TurumShopifySync/HSH.TurumShopifySync.csproj --configuration Release

      - name: Run app
        run: ./HSH.TurumShopifySync/bin/Release/HSH.TurumShopifySync.exe
        env:
          SHOPIFY_CLIENT_ID: ${{ secrets.SHOPIFY_CLIENT_ID }}
          SHOPIFY_CLIENT_SECRET: ${{ secrets.SHOPIFY_CLIENT_SECRET }}
          TURUM_PASSWORD: ${{ secrets.TURUM_PASSWORD }}
          TURUM_USERNAME: ${{ secrets.TURUM_USERNAME }}
