name: Daily Run

on:
  schedule:
    - cron: '0 0 * * *'    # once a day at midnight
  workflow_dispatch:
jobs:
  run:
    runs-on: windows-latest  # changed from ubuntu-latest
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@v4

      - name: Restore packages
        run: dotnet restore ./HSH.TurumShopifySync/HSH.TurumShopifySync.csproj

      - name: Run app
        run: dotnet run --project ./HSH.TurumShopifySync
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}
