name: Hourly Run

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run:
    runs-on: windows-latest  # changed from ubuntu-latest
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@v4

      - name: Run app
        run: dotnet run --project ./HSH.TurumShopifySync  # adjust path
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}
